# Generated by Django 3.2.17 on 2023-02-10 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='genero',
            fields=[
                ('codgenero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reseña', models.CharField(max_length=50)),
                ('puntuacion', models.CharField(max_length=20)),
                ('director', models.CharField(max_length=40)),
                ('descripcion', models.TextField(blank=True)),
                ('contenido', models.CharField(blank=True, max_length=40)),
                ('imagen', models.ImageField(blank=True, upload_to='tapas')),
                ('estado', models.BooleanField(default=True)),
                ('sipnosis', models.TextField(blank=True)),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.genero')),
            ],
        ),
    ]
