# Generated by Django 4.2.7 on 2023-11-09 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(blank=True, max_length=30, null=True)),
                ('state', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Genero',
                'verbose_name_plural': 'Generos',
                'ordering': ['genre'],
            },
        ),
        migrations.CreateModel(
            name='TypePerson',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Actor_Actress', 'Actor_Actress'), ('Director', 'Director'), ('Producer', 'Producer')], max_length=15)),
                ('state', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TypePerson',
                'verbose_name_plural': 'TypePerson',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('lastname', models.CharField(max_length=180)),
                ('firstname', models.CharField(max_length=180)),
                ('aliases', models.CharField(blank=True, max_length=80, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='person')),
                ('state', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('typeperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='core.typeperson')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
                'ordering': ['firstname'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('sipnosis', models.TextField(blank=True, null=True)),
                ('release_year', models.IntegerField()),
                ('lenguage', models.CharField(max_length=20)),
                ('top', models.ImageField(blank=True, null=True, upload_to='movies')),
                ('state', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Actor_Actress', models.ManyToManyField(related_name='actor_actress', to='core.person')),
                ('Director', models.ManyToManyField(related_name='director', to='core.person')),
                ('Producer', models.ManyToManyField(related_name='producer', to='core.person')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.genre')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comments_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('state', models.BooleanField(default=True)),
                ('commentmovie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentmovie', to='core.movie')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['comment'],
            },
        ),
    ]
